name: RECControlPanel
channels:
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - intel-openmp=2024.2.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.6
  - libhwloc=2.11.2
  - libiconv=1.18
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libsqlite=3.49.1
  - libwinpthread=12.0.0.r4.gg4f2fc60ca
  - libxml2=2.13.7
  - libzlib=1.3.1
  - mkl=2024.2.2
  - numpy=2.0.2
  - openssl=3.4.1
  - pandas=2.2.3
  - pip=25.0.1
  - pyserial=3.5
  - python=3.9.21
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.9
  - pytz=2024.1
  - setuptools=78.1.0
  - six=1.17.0
  - tbb=2021.13.0
  - tk=8.6.13
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.42.34438
  - wheel=0.45.1
